import correlations

selector = {
    ("Natural convection", "Internal", "Narrow vertical duct", "Parallel plates", None): correlations.internalNaturalConvectionNarrowVerticalDuct,
    ("Natural convection", "Internal", "Narrow vertical duct", "Circular", None): correlations.internalNaturalConvectionNarrowVerticalDuct,
    ("Natural convection", "Internal", "Narrow vertical duct", "Squared", None): correlations.internalNaturalConvectionNarrowVerticalDuct,
    ("Natural convection", "Internal", "Narrow vertical duct", "Equilateral triangle", None): correlations.internalNaturalConvectionNarrowVerticalDuct,
    ("Natural convection", "Internal", "Vertical rectangular cavity", None, None): correlations.internalNaturalConvectionVerticalRectangularCavity,
    ("Natural convection", "Internal", "Inclined rectangular cavity", None, None): correlations.internalNaturalConvectionInclinedRectangularCavity,
    ("Natural convection", "Internal", "Horizontal rectangular cavity", None, None): correlations.internalNaturalConvectionHorizontalRectangularCavity,
    ("Natural convection", "Internal", "Spherical cavity", None, None): correlations.internalNaturalConvectionSphericalCavity,
    ("Natural convection", "Internal", "Concentric cylinders", None, None): correlations.internalNaturalConvectionConcentricCylinders,
    ("Natural convection", "Internal", "Concentric spheres", None, None): correlations.internalNaturalConvectionConcentricSpheres,
    ("Natural convection", "External", "Vertical flat plate", None, None): correlations.externalNaturalConvectionVerticalFlatPlate,
    ("Natural convection", "External", "Inclined flat plate", None, None): correlations.externalNaturalConvectionInclinedFlatPlate,
    ("Natural convection", "External", "Horizontal flat plate", "Hot top surface or cold bottom surface", None): correlations.externalNaturalConvectionHorizontalFlatPlateTopHot,
    ("Natural convection", "External", "Horizontal flat plate", "Cold top surface or hot bottom surface", None): correlations.externalNaturalConvectionHorizontalFlatPlateTopCold,
    ("Natural convection", "External", "Sphere", None, None): correlations.externalNaturalConvectionSphere,
    ("Natural convection", "External", "Vertical cylinder", None, None): correlations.externalNaturalConvectionVerticalCylinder,
    ("Natural convection", "External", "Inclined cylinder", None, None): correlations.externalNaturalConvectionInclinedCylinder,
    ("Natural convection", "External", "Horizontal cylinder", None, None): correlations.externalNaturalConvectionHorizontalCylinder,
    ("Forced convection", "Internal", "Circular duct", None, None): correlations.internalForcedConvectionCircularDuct,
    ("Forced convection", "Internal", "Non-circular duct", "Triangular", "Constant temperature"): correlations.internalForcedConvectionTriangularDuctConstantT,
    ("Forced convection", "Internal", "Non-circular duct", "Triangular", "Constant heat flow"): correlations.internalForcedConvectionTriangularDuctConstantQ,
    ("Forced convection", "Internal", "Non-circular duct", "Squared", "Constant temperature"): correlations.internalForcedConvectionSquaredDuctConstantT,
    ("Forced convection", "Internal", "Non-circular duct", "Squared", "Constant heat flow"): correlations.internalForcedConvectionSquaredDuctConstantQ,
    ("Forced convection", "Internal", "Non-circular duct", "Rectangular", "Constant temperature"): correlations.internalForcedConvectionRectangularDuctConstantT,
    ("Forced convection", "Internal", "Non-circular duct", "Rectangular", "Constant heat flow"): correlations.internalForcedConvectionRectangularDuctConstantQ,
    ("Forced convection", "Internal", "Between parallel planes", None, None): correlations.internalForcedConvectionBetweenParallelPlanes,
    ("Forced convection", "Internal", "Annular duct", "Inner heat flow", None): correlations.internalForcedConvectionAnnularDuctInnerHeatFlow,
    ("Forced convection", "Internal", "Annular duct", "Outer heat flow", None): correlations.internalForcedConvectionAnnularDuctOuterHeatFlow,
    ("Forced convection", "Internal", "Annular duct", "Inner-outer heat flow", None): correlations.internalForcedConvectionAnnularDuctInnerOuterHeatFlow,
    ("Forced convection", "Internal", "Helical coil", None, None): correlations.internalForcedConvectionHelicalCoil,
    ("Forced convection", "External", "Flat plate", None, None): correlations.externalForcedConvectionFlatPlate,
    ("Forced convection", "External", "Cylinders with perpendicular flow", None, None): correlations.externalForcedConvectionPerpendicularFlowCylinders,
    ("Forced convection", "External", "Other geometries with perpendicular flow", "Square (face oriented)", None): correlations.externalForcedConvectionPerpendicularFlowSquareFaceOriented,
    ("Forced convection", "External", "Other geometries with perpendicular flow", "Square (arist oriented)", None): correlations.externalForcedConvectionPerpendicularFlowSquareAristOriented,
    ("Forced convection", "External", "Other geometries with perpendicular flow", "Hexagon (face oriented)", None): correlations.externalForcedConvectionPerpendicularFlowHexagonFaceOriented,
    ("Forced convection", "External", "Other geometries with perpendicular flow", "Hexagon (arist oriented)", None): correlations.externalForcedConvectionPerpendicularFlowHexagonAristOriented,
    ("Forced convection", "External", "Other geometries with perpendicular flow", "Rectangle (face oriented)", None): correlations.externalForcedConvectionPerpendicularFlowRectangleFaceOriented,
    ("Forced convection", "External", "Other geometries with perpendicular flow", "Ellipse (wide surface oriented)", None): correlations.externalForcedConvectionPerpendicularFlowEllipseWideOriented,
    ("Forced convection", "External", "Other geometries with perpendicular flow", "Ellipse (narrow surface oriented)", None): correlations.externalForcedConvectionPerpendicularFlowEllipseNarrowOriented,
    ("Forced convection", "External", "Sphere", None, None): correlations.externalForcedConvectionSphere,
    ("Forced convection", "External", "Cross-flow tube bundle", "Square pitch", None): correlations.externalForcedConvectionCrossFlowTubeBundleSquare,
    ("Forced convection", "External", "Cross-flow tube bundle", "Triangular pitch", None): correlations.externalForcedConvectionCrossFlowTubeBundleTriangular,
    ("Natural condensation", None, "Vertical flat surface", None, None): correlations.naturalCondensationVerticalFlatSurface,
    ("Natural condensation", None, "Inclined flat surface", None, None): correlations.naturalCondensationInclinedFlatSurface,
    ("Natural condensation", None, "Horizontal flat surface", "Strip", None): correlations.naturalCondensationHorizontalFlatSurfaceStrip,
    ("Natural condensation", None, "Horizontal flat surface", "Disk", None): correlations.naturalCondensationHorizontalFlatSurfaceDisk,
    ("Natural condensation", None, "Horizontal flat surface", "Other strip", None): correlations.naturalCondensationHorizontalFlatSurfaceOtherStrip,
    ("Natural condensation", None, "Horizontal flat surface", "Other disk", None): correlations.naturalCondensationHorizontalFlatSurfaceOtherDisk,
    ("Natural condensation", None, "Vertical cylinder", None, None): correlations.naturalCondensationVerticalCylinder,
    ("Natural condensation", None, "Inclined cylinder", None, None): correlations.naturalCondensationInclinedCylinder,
    ("Natural condensation", None, "Horizontal cylinder", None, None): correlations.naturalCondensationHorizontalCylinder,
    ("Natural condensation", None, "Horizontal tube bundle", None, None): correlations.naturalCondensationHorizontalTubeBundle,
    ("Natural condensation", None, "Sphere", None, None): correlations.naturalCondensationSphere,
    ("Forced condensation", "Internal", "Circular duct", None, None): correlations.internalForcedCondensationCircularDuct,
    ("Forced condensation", "External", "Horizontal cylinder", None, None): correlations.externalForcedCondensationHorizontalCircularDuct,
}


def getCorrelation(keyTupleInputs):
    return selector[keyTupleInputs]